(() => {
const $=NINJA.$;
NINJA.Draw={ctx:null,tool:'pen',drawing:false,start:null,current:[],strokes:[],redoStack:[],
 init(){this.ctx=$('draw').getContext('2d');addEventListener('resize',()=>this.resize());setTimeout(()=>this.resize(),50);$('draw').onpointerdown=e=>this.down(e);$('draw').onpointermove=e=>this.move(e);$('draw').onpointerup=e=>this.up(e);['pen','line','arrow','circle','rect'].forEach(id=>$(id).onclick=()=>this.setTool(id));$('undo').onclick=()=>{NINJA.Recorder.pause('書き込み修正中');if(this.strokes.length){this.redoStack.push(this.strokes.pop());this.redraw()}};$('redo').onclick=()=>{NINJA.Recorder.pause('書き込み修正中');if(this.redoStack.length){this.strokes.push(this.redoStack.pop());this.redraw()}};$('clear').onclick=()=>this.clear(true)},
 resize(){const c=$('draw'),b=$('videoBox');c.width=b.clientWidth;c.height=b.clientHeight;this.redraw()},pos(e){const r=$('draw').getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}},setTool(t){this.tool=t;document.querySelectorAll('#pen,#line,#arrow,#circle,#rect').forEach(b=>b.classList.remove('active'));$(t).classList.add('active')},
 down(e){NINJA.Recorder.pause('ペン・画面操作中');NINJA.Video.pause();this.drawing=true;this.start=this.pos(e);this.current=[this.start];$('draw').setPointerCapture(e.pointerId)},move(e){if(!this.drawing)return;this.current.push(this.pos(e));this.redraw()},up(e){if(!this.drawing)return;this.drawing=false;const end=this.pos(e),pts=(this.tool==='pen'||this.tool==='arrow')?this.current:[this.start,end];this.strokes.push({type:this.tool,points:pts,color:'#ff2222',w:4});this.redoStack=[];this.current=[];this.redraw()},
 simplify(p,d=5){if(p.length<3)return p;const o=[p[0]];for(let i=1;i<p.length-1;i++){const l=o[o.length-1],pt=p[i];if(Math.hypot(pt.x-l.x,pt.y-l.y)>=d)o.push(pt)}o.push(p[p.length-1]);return o},smooth(p){let pts=this.simplify(p,6);for(let pass=0;pass<2;pass++){const o=[pts[0]];for(let i=1;i<pts.length-1;i++)o.push({x:(pts[i-1].x+pts[i].x+pts[i+1].x)/3,y:(pts[i-1].y+pts[i].y+pts[i+1].y)/3});o.push(pts[pts.length-1]);pts=o}return pts},curve(ctx,pts){ctx.moveTo(pts[0].x,pts[0].y);if(pts.length===2){ctx.lineTo(pts[1].x,pts[1].y);return}for(let i=1;i<pts.length-1;i++){const m={x:(pts[i].x+pts[i+1].x)/2,y:(pts[i].y+pts[i+1].y)/2};ctx.quadraticCurveTo(pts[i].x,pts[i].y,m.x,m.y)}ctx.lineTo(pts[pts.length-1].x,pts[pts.length-1].y)},
 drawStroke(s,ctx=this.ctx,sx=1,sy=1){ctx.strokeStyle=s.color||'#ff2222';ctx.lineWidth=(s.w||4)*((sx+sy)/2);ctx.lineCap='round';ctx.lineJoin='round';const pts=(s.type==='pen'?this.smooth(s.points):s.points).map(p=>({x:p.x*sx,y:p.y*sy}));ctx.beginPath();if(s.type==='pen'){this.curve(ctx,pts);ctx.stroke()}if(s.type==='line'){ctx.moveTo(pts[0].x,pts[0].y);ctx.lineTo(pts[1].x,pts[1].y);ctx.stroke()}if(s.type==='arrow'){const c=this.smooth(pts);this.curve(ctx,c);ctx.stroke();const b=c[c.length-1],a=c[Math.max(0,c.length-3)]||c[0],ang=Math.atan2(b.y-a.y,b.x-a.x),len=20*((sx+sy)/2);ctx.beginPath();ctx.moveTo(b.x,b.y);ctx.lineTo(b.x-len*Math.cos(ang-.55),b.y-len*Math.sin(ang-.55));ctx.moveTo(b.x,b.y);ctx.lineTo(b.x-len*Math.cos(ang+.55),b.y-len*Math.sin(ang+.55));ctx.stroke()}if(s.type==='circle'){const a=pts[0],b=pts[1];ctx.beginPath();ctx.ellipse((a.x+b.x)/2,(a.y+b.y)/2,Math.abs(b.x-a.x)/2,Math.abs(b.y-a.y)/2,0,0,Math.PI*2);ctx.stroke()}if(s.type==='rect'){const a=pts[0],b=pts[1];ctx.strokeRect(a.x,a.y,b.x-a.x,b.y-a.y)}},
 drawAll(ctx=this.ctx,sx=1,sy=1){this.strokes.forEach(s=>this.drawStroke(s,ctx,sx,sy))},redraw(){this.ctx.clearRect(0,0,$('draw').width,$('draw').height);this.drawAll();if(this.drawing&&this.current.length)this.drawStroke({type:this.tool,points:(this.tool==='pen'||this.tool==='arrow')?this.current:[this.start,this.current[this.current.length-1]],color:'#ff2222',w:4})},clear(pause=true){if(pause)NINJA.Recorder.pause('書き込み修正中');this.strokes=[];this.redoStack=[];this.redraw()},export(){return JSON.parse(JSON.stringify(this.strokes))},import(v){this.strokes=JSON.parse(JSON.stringify(v||[]));this.redoStack=[];this.redraw()}
};
})();