(() => {
const $=NINJA.$, U=NINJA.Utils;
NINJA.Recorder={
 media:null,chunks:[],canvas:null,ctx:null,timer:null,isRecording:false,isPaused:false,
 init(){ $('recStart').onclick=()=>this.start(); $('recStop').onclick=()=>this.stop(); $('shot').onclick=()=>this.saveImage(); },
 pause(reason='編集中'){ if(!this.isRecording||this.isPaused||!this.media)return; if(this.media.state==='recording')try{this.media.pause()}catch(e){} this.isPaused=true;$('recStart').textContent='● 録画一時停止中';U.status('録画一時停止：'+reason); },
 resume(delay=0){ if(!this.isRecording||!this.isPaused||!this.media)return; setTimeout(()=>{ if(this.media&&this.media.state==='paused')try{this.media.resume()}catch(e){} this.isPaused=false;$('recStart').textContent='● 録画中';U.status('録画再開');NINJA.Video.play(); },delay); },
 size(){ const q=$('quality').value,sw=$('video').videoWidth||1280,sh=$('video').videoHeight||720; if(q==='light'){const s=Math.min(1,1280/sw);return{w:Math.round(sw*s),h:Math.round(sh*s),fps:30,bitrate:6000000}} if(q==='max')return{w:sw,h:sh,fps:60,bitrate:28000000}; return{w:sw,h:sh,fps:30,bitrate:16000000}; },
 drawComposite(ctx,w,h){ ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';ctx.fillStyle='#000';ctx.fillRect(0,0,w,h);const v=$('video');if(v.videoWidth)ctx.drawImage(v,0,0,w,h);NINJA.Draw.drawAll(ctx,w/$('draw').width,h/$('draw').height);const f=$('floatText');if(f.style.display!=='none'&&f.textContent){const text=f.textContent;ctx.font='bold 42px sans-serif';ctx.textAlign='center';const tw=Math.min(ctx.measureText(text).width+70,w*.86),x=w/2-tw/2,y=h*.82;ctx.fillStyle='rgba(0,0,0,.72)';ctx.fillRect(x,y,tw,74);ctx.fillStyle='#fff';ctx.fillText(text,w/2,y+50,tw-30);} },
 start(){ if(NINJA.Video.mode!=='mp4'){alert('YouTubeモードでは映像込み録画はできません。');return} if(!$('video').src){alert('先にMP4を読み込んでください');return} const q=this.size();this.canvas=document.createElement('canvas');this.canvas.width=q.w;this.canvas.height=q.h;this.ctx=this.canvas.getContext('2d',{alpha:false,desynchronized:true});const stream=this.canvas.captureStream(q.fps);if($('video').captureStream)try{$('video').captureStream().getAudioTracks().forEach(t=>stream.addTrack(t))}catch(e){} const types=['video/webm;codecs=vp9','video/webm;codecs=vp8','video/webm'];const mimeType=types.find(t=>MediaRecorder.isTypeSupported(t))||'';const opt=mimeType?{mimeType,videoBitsPerSecond:q.bitrate}:{videoBitsPerSecond:q.bitrate};try{this.media=new MediaRecorder(stream,opt)}catch(e){alert('Chromeで試してください');return}this.chunks=[];this.media.ondataavailable=e=>{if(e.data.size)this.chunks.push(e.data)};this.media.onstop=()=>{clearInterval(this.timer);this.isRecording=false;this.isPaused=false;$('recStart').textContent='● 録画開始';$('recStop').classList.add('disabled');U.download('ninja_analysis_record.webm',new Blob(this.chunks,{type:'video/webm'}));U.status('録画を保存しました')};this.timer=setInterval(()=>this.drawComposite(this.ctx,this.canvas.width,this.canvas.height),1000/q.fps);this.media.start(1000);this.isRecording=true;$('recStart').textContent='● 録画中';$('recStop').classList.remove('disabled');U.status('録画中'); },
 stop(){if(this.media&&(this.media.state==='recording'||this.media.state==='paused'))this.media.stop()},
 saveImage(){if(NINJA.Video.mode!=='mp4'){alert('YouTubeモードでは映像込み画像保存はできません。');return}const v=$('video'),c=document.createElement('canvas'),ctx=c.getContext('2d');c.width=v.videoWidth||1280;c.height=v.videoHeight||720;this.drawComposite(ctx,c.width,c.height);U.download('ninja_scene.png',c.toDataURL('image/png'))}
};
})();